// Code generated by counterfeiter. DO NOT EDIT.
package agentserverfakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-agent/v2/agentserver"
)

type FakeDirectorClient struct {
	ProvideDiskStub        func(agentserver.ProvideDiskDirectorRequest) (agentserver.ProvideDiskDirectorResponse, error)
	provideDiskMutex       sync.RWMutex
	provideDiskArgsForCall []struct {
		arg1 agentserver.ProvideDiskDirectorRequest
	}
	provideDiskReturns struct {
		result1 agentserver.ProvideDiskDirectorResponse
		result2 error
	}
	provideDiskReturnsOnCall map[int]struct {
		result1 agentserver.ProvideDiskDirectorResponse
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDirectorClient) ProvideDisk(arg1 agentserver.ProvideDiskDirectorRequest) (agentserver.ProvideDiskDirectorResponse, error) {
	fake.provideDiskMutex.Lock()
	ret, specificReturn := fake.provideDiskReturnsOnCall[len(fake.provideDiskArgsForCall)]
	fake.provideDiskArgsForCall = append(fake.provideDiskArgsForCall, struct {
		arg1 agentserver.ProvideDiskDirectorRequest
	}{arg1})
	stub := fake.ProvideDiskStub
	fakeReturns := fake.provideDiskReturns
	fake.recordInvocation("ProvideDisk", []interface{}{arg1})
	fake.provideDiskMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDirectorClient) ProvideDiskCallCount() int {
	fake.provideDiskMutex.RLock()
	defer fake.provideDiskMutex.RUnlock()
	return len(fake.provideDiskArgsForCall)
}

func (fake *FakeDirectorClient) ProvideDiskCalls(stub func(agentserver.ProvideDiskDirectorRequest) (agentserver.ProvideDiskDirectorResponse, error)) {
	fake.provideDiskMutex.Lock()
	defer fake.provideDiskMutex.Unlock()
	fake.ProvideDiskStub = stub
}

func (fake *FakeDirectorClient) ProvideDiskArgsForCall(i int) agentserver.ProvideDiskDirectorRequest {
	fake.provideDiskMutex.RLock()
	defer fake.provideDiskMutex.RUnlock()
	argsForCall := fake.provideDiskArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeDirectorClient) ProvideDiskReturns(result1 agentserver.ProvideDiskDirectorResponse, result2 error) {
	fake.provideDiskMutex.Lock()
	defer fake.provideDiskMutex.Unlock()
	fake.ProvideDiskStub = nil
	fake.provideDiskReturns = struct {
		result1 agentserver.ProvideDiskDirectorResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeDirectorClient) ProvideDiskReturnsOnCall(i int, result1 agentserver.ProvideDiskDirectorResponse, result2 error) {
	fake.provideDiskMutex.Lock()
	defer fake.provideDiskMutex.Unlock()
	fake.ProvideDiskStub = nil
	if fake.provideDiskReturnsOnCall == nil {
		fake.provideDiskReturnsOnCall = make(map[int]struct {
			result1 agentserver.ProvideDiskDirectorResponse
			result2 error
		})
	}
	fake.provideDiskReturnsOnCall[i] = struct {
		result1 agentserver.ProvideDiskDirectorResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeDirectorClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.provideDiskMutex.RLock()
	defer fake.provideDiskMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDirectorClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ agentserver.DirectorClient = new(FakeDirectorClient)
